spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled: true
  datasource:
    jpa: mysql
      hikari:
        maximum-pool-size: 5
        data-source-properties:
          #recommended settings for MySql
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false