#this is default configuration provided by Spring Boot
#good practice is to mimic any database vendor what you're planning to use, for example MYSQL, ORACLE etc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: beer_inventory_service
    password: password
  #update for developmnet, #validate for production
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

    #    logging:
    #      level:
    #        com:
    #          zaxxer:
    #            hikari:
    #              HikariConfig: DEBUG
    #        org:
    #          hibernate:
    #            SQL: DEBUG
    #            type:
    #              desciptor:
    #                sql:
    #                  BasicBinder: TRACE
